trigger:
- main

pool:
  name: Default

steps:
- checkout: self

- script: java -version
  displayName: Check Java

- script: mvn -version
  displayName: Check Maven

- script: mvn clean test package
  displayName: Maven Build

- script: python scripts/post_build.py
  displayName: Run Python script
